### PR TITLE
Feat/orgs db

### PR DESCRIPTION
**Pull request by jvmontes**
Work in progress PR to add organizations to a database. I still need to do more work to incorporate the Industries and finish that work to the UI we had, but I wanted to get this up just to get a review and some eyes on it. I'll plan on continuing the Industry table work on a separate branch. 

- Remove city, region, and industry columns from organizations table. Industry will be handled in a separate table, and city/region will most likely be handled on a chapter-by-chapter basis as a child of the parent org. 
- Create an Industries table + a join table OrganizationIndustries.
- Add api/organizations Next.js route
- Add dbOperations to call fetchOrganizations using drizzleClient
- Comment out industry logic until new PR addresses this using the DB.

### CODE REVIEW

**Comment by rogeruiz** [comment]
With the work I'm doing in #28, I feel like we're missing some columns in our organization table. 

According to the designs, we have content blocks for a number of things that aren't in the Mock Directory structure or in this PR. 

I'm thinking we need the following schema for the organization. What do you think??

- [x] name
- [x] logo url
- [x] description
- [ ] sub-heading / short description
- [x] website url
- [x] industries
- [ ] affinities

The ones I don't see in this PR or #29 don't have the items that are not checked above.

**Comment by jvmontes** [comment]
> With the work I'm doing in #28, I feel like we're missing some columns in our organization table.
> 
> According to the designs, we have content blocks for a number of things that aren't in the Mock Directory structure or in this PR.
> 
> I'm thinking we need the following schema for the organization. What do you think??
> 
> * [x]  name
> * [x]  logo url
> * [x]  description
> * [ ]  sub-heading / short description
> * [x]  website url
> * [x]  industries
> * [ ]  affinities
> 
> The ones I don't see in this PR or #29 don't have the items that are not checked above.

Yes, you're right. short_description is missing from this schema. I can add that in. I also agree that affinities is missing, I just wanted to get some of the main pieces together and potentially allow someone else on the team to build up the affinities (maybe Gera, Oscar, or Francisco).

**Comment by jvmontes** [comment]
> With the work I'm doing in #28, I feel like we're missing some columns in our organization table.
> 
> According to the designs, we have content blocks for a number of things that aren't in the Mock Directory structure or in this PR.
> 
> I'm thinking we need the following schema for the organization. What do you think??
> 
> * [x]  name
> * [x]  logo url
> * [x]  description
> * [ ]  sub-heading / short description
> * [x]  website url
> * [x]  industries
> * [ ]  affinities
> 
> The ones I don't see in this PR or #29 don't have the items that are not checked above.

@rogeruiz Check out the changes in this commit. Basically I just updated the schema.ts & re-ran a migration

https://github.com/Alacran-Studio/lpdd/pull/29/commits/86d5ed6a8eef1429115254bbb8f60bd41335a767

This should address a couple tickets on Asana spawning from this PR. If it looks good to you, give it an approval. I'll get started on the changes for the industries-db branch (#30).

**Comment by rogeruiz** [comment]
lgtm 🌈 

Approved by the approval of #30 🚀

**Comment by jvmontes** [comment]
Merged #30 into this PR so this is all the DB changes. 

From the other PR:
>update seed files to seed organizations, industries, and organization industries.
add api route for api/industries
Directory component to fetch industries list from db
dbOperations to get industries list, organization Industry mappings (1871 has Tech and Venture Capital), and massage organizations to add industry data.

**Comment by jvmontes** [comment]
I mentioned to @rogeruiz that we should probably hold off on merging this until every dev on the team has the database set up on their machine..

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

I've been using this and been doing dev work against these changes doing well.

**Pull request merged**
